export const beams = [
  {
    initialX: 10,
    translateX: 10,
    duration: 7,
    repeatDelay: 3,
    delay: 2,
  },
  {
    initialX: 600,
    translateX: 600,
    duration: 3,
    repeatDelay: 3,
    delay: 4,
  },
  {
    initialX: 100,
    translateX: 100,
    duration: 7,
    repeatDelay: 7,
    className: "h-6",
  },
  {
    initialX: 400,
    translateX: 400,
    duration: 5,
    repeatDelay: 14,
    delay: 4,
  },
  {
    initialX: 800,
    translateX: 800,
    duration: 11,
    repeatDelay: 2,
    className: "h-20",
  },
  {
    initialX: 1000,
    translateX: 1000,
    duration: 4,
    repeatDelay: 2,
    className: "h-12",
  },
  {
    initialX: 1200,
    translateX: 1200,
    duration: 6,
    repeatDelay: 4,
    delay: 2,
    className: "h-6",
  },

  {
    initialX: 1400,
    translateX: 1400,
    duration: 8,
    repeatDelay: 4,
    delay: 2,
    className: "h-6",
  },
  {
    initialX: 1600,
    translateX: 1600,
    duration: 8,
    repeatDelay: 4,
    delay: 2,
    className: "h-6",
  },
  {
    initialX: 1800,
    translateX: 1800,
    duration: 5,
    repeatDelay: 14,
    delay: 2,
    className: "h-12",
  },
  {
    initialX: 2000,
    translateX: 2000,
    duration: 11,
    repeatDelay: 4,
    delay: 2,
    className: "h-20",
  },
];
